# IBM Developer's Workframe/2 Make File Creation run at 18:14:33 on 07/15/92

# Make File Creation run in directory:
#   D:\WPSDEMOS\WHOAMI;

# Assumed INCLUDE environment variable path:
#   G:\IBMC\INCLUDE;
#   G:\TOOLKT20\C\OS2H;
#   G:\TOOLKT20\ASM\OS2INC;


WHOAMI.OBJ:  WHOAMI.C  \
   {.;$(INCLUDE);}whoami.ih  \
#    {$(INCLUDE);}os2.h  \
     {.;$(INCLUDE);}whoami.h  \
#      {$(INCLUDE);}som.h  \
       {.;$(INCLUDE);}wpabs.h  \
#        {$(INCLUDE);}som.h  \
         {.;$(INCLUDE);}wpobject.h  \
#          {$(INCLUDE);}pmstddlg.h  \
#          {$(INCLUDE);}som.h  \
#          {$(INCLUDE);}somobj.h  \
   MAKEFILE
