
/*
 * This file was generated by the SOM Compiler.
 * FileName: whoami.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define Whoami_Class_Source
#include "whoami.ih"

SOM_Scope MRESULT   SOMLINK wpDrop(Whoami *somSelf,
		HWND hwndCnr,
		PDRAGINFO pdrgInfo,
		PDRAGITEM pdrgItem)
{
    char szDataType[80];

    /* WhoamiData *somThis = WhoamiGetData(somSelf); */
    WhoamiMethodDebug("Whoami","wpDrop");

       DrgQueryStrName(pdrgItem->hstrSourceName, 80, szDataType);
        WinMessageBox(HWND_DESKTOP,
                      HWND_DESKTOP,
                      szDataType,
                      "Who Am I?",
                      0,
                      MB_NOICON | MB_OK | MB_MOVEABLE);

        return 0;

//    return (parent_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem));
}
