
/*
 * This file was generated by the SOM Compiler.
 * FileName: graduate.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define GraduateStudent_Class_Source
#include "graduate.ih"

SOM_Scope void   SOMLINK printStudentInfo(GraduateStudent *somSelf)
{
    GraduateStudentData *somThis = GraduateStudentGetData(somSelf);
    GraduateStudentMethodDebug("GraduateStudent","printStudentInfo");

    parent_printStudentInfo(somSelf);
    printf( "             Thesis   : %s\n", _thesis );
    printf( "             Degree   : %s\n", _degree );
}

SOM_Scope char *  SOMLINK getStudentType(GraduateStudent *somSelf)
{
    static char *type = "Graduate";
    GraduateStudentData *somThis = GraduateStudentGetData(somSelf);
    GraduateStudentMethodDebug("GraduateStudent","getStudentType");

    return type;
}

SOM_Scope void   SOMLINK setUpGraduateStudent(GraduateStudent *somSelf,
                char *id,
                char *name,
                char *thesis,
                char *degree)
{
    GraduateStudentData *somThis = GraduateStudentGetData(somSelf);
    GraduateStudentMethodDebug("GraduateStudent","setUpGraduateStudent");

    _setUpStudent( somSelf, id, name );   // call base class initializer first
    strcpy( _thesis, thesis );
    strcpy( _degree, degree );
}
