
/*
 * This file was generated by the SOM Compiler.
 * FileName: undrgrad.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define UnderGraduateStudent_Class_Source
#include "undrgrad.ih"

SOM_Scope void   SOMLINK printStudentInfo(UnderGraduateStudent *somSelf)
{
    UnderGraduateStudentData *somThis = UnderGraduateStudentGetData(somSelf);
    UnderGraduateStudentMethodDebug("UnderGraduateStudent","printStudentInfo");

    parent_printStudentInfo(somSelf);
    printf( "             Grad Date: %s\n", _date );
}

SOM_Scope char *  SOMLINK getStudentType(UnderGraduateStudent *somSelf)
{
    static char *type = "UnderGraduate";
    UnderGraduateStudentData *somThis = UnderGraduateStudentGetData(somSelf);
    UnderGraduateStudentMethodDebug("UnderGraduateStudent","getStudentType");

    return type;
}

SOM_Scope void   SOMLINK setUpUnderGraduateStudent(UnderGraduateStudent *somSelf,
                char *id,
                char *name,
                char *date )
{
    UnderGraduateStudentData *somThis = UnderGraduateStudentGetData(somSelf);
    UnderGraduateStudentMethodDebug("UnderGraduateStudent","setUpUnderGraduateStudent");

    _setUpStudent( somSelf, id, name );
    strcpy( _date, date );
}
