
/*
 * This file was generated by the SOM Compiler.
 * FileName: foot.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define OneFoot_Class_Source
#include "foot.ih"

SOM_Scope MRESULT   SOMLINK Foot_wpDrop(OneFoot *somSelf,
		HWND hwndCnr,
		PDRAGINFO pdrgInfo,
		PDRAGITEM pdrgItem)
{

    OneFootData *somThis = OneFootGetData(somSelf);
    OneFootMethodDebug("OneFoot","Foot_wpDrop");
        WinMessageBox(HWND_DESKTOP,
                      HWND_DESKTOP,
                      "OUCH!! Don't drop that on my foot!",
                      "Foot",
                      0,
                      MB_NOICON | MB_OK | MB_MOVEABLE);

//    return (parent_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem));
      return 0;
}

SOM_Scope HWND   SOMLINK Foot_wpOpen(OneFoot *somSelf,
		HWND hwndCnr,
		ULONG ulView,
		ULONG param)
{
    OneFootData *somThis = OneFootGetData(somSelf);
    OneFootMethodDebug("OneFoot","Foot_wpOpen");
        if (ulView == OPEN_SETTINGS)
	  return (parent_wpOpen(somSelf,hwndCnr,ulView,param));
	else
	{ 
          WinMessageBox(HWND_DESKTOP,
                        HWND_DESKTOP,
                        "How do you expect to open a foot?",
                        "Foot",
                        0,
                        MB_NOICON | MB_OK | MB_MOVEABLE);
	  return 0;
	}
}
